apiVersion: v1
kind: Service
metadata:
  name: exchange-service
  labels:
    app: exchange-service
spec:
  type: ClusterIP
  selector:
    app: exchange-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9009
